/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ListaController;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;


/**
 *
 * 
 */
public class Lista extends javax.swing.JFrame {

    private final ListaController controller;
    private JFormattedTextField jTextField1;

    /**
     * Creates new form Agenda
     */
    public Lista() {
        initComponents();
        controller = new ListaController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelConcluirPedido = new javax.swing.JLabel();
        LabelId = new javax.swing.JLabel();
        LabelCliente = new javax.swing.JLabel();
        LabelPedido = new javax.swing.JLabel();
        LabelValor = new javax.swing.JLabel();
        LabelData = new javax.swing.JLabel();
        LabelHora = new javax.swing.JLabel();
        LabelObservacao = new javax.swing.JLabel();
        TextId = new javax.swing.JTextField();
        JComboBoxCliente = new javax.swing.JComboBox<>();
        JComboBoxPedido = new javax.swing.JComboBox<>();
        TextValor = new javax.swing.JTextField();
        TextFormatedData = new javax.swing.JFormattedTextField();
        TextFormatedHora = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextObservacao = new javax.swing.JTextArea();
        ButtonPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableListaPedido = new javax.swing.JTable();
        jLabelPainelPedido = new javax.swing.JLabel();
        LabelPedidoFundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelConcluirPedido.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        LabelConcluirPedido.setForeground(new java.awt.Color(255, 255, 255));
        LabelConcluirPedido.setText("Pedido");
        getContentPane().add(LabelConcluirPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 150, 60));

        LabelId.setForeground(new java.awt.Color(255, 255, 255));
        LabelId.setText("Id");
        getContentPane().add(LabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        LabelCliente.setForeground(new java.awt.Color(255, 255, 255));
        LabelCliente.setText("Cliente");
        getContentPane().add(LabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        LabelPedido.setForeground(new java.awt.Color(255, 255, 255));
        LabelPedido.setText("Pedido");
        getContentPane().add(LabelPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        LabelValor.setForeground(new java.awt.Color(255, 255, 255));
        LabelValor.setText("Valor R$");
        getContentPane().add(LabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        LabelData.setForeground(new java.awt.Color(255, 255, 255));
        LabelData.setText("Data");
        getContentPane().add(LabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        LabelHora.setForeground(new java.awt.Color(255, 255, 255));
        LabelHora.setText("Hora");
        getContentPane().add(LabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        LabelObservacao.setForeground(new java.awt.Color(255, 255, 255));
        LabelObservacao.setText("Observação");
        getContentPane().add(LabelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        TextId.setEditable(false);
        TextId.setText("10");
        TextId.setToolTipText("");
        TextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIdActionPerformed(evt);
            }
        });
        getContentPane().add(TextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 280, 40));

        JComboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxClienteActionPerformed(evt);
            }
        });
        getContentPane().add(JComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 280, 40));

        JComboBoxPedido.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JComboBoxPedidoItemStateChanged(evt);
            }
        });
        getContentPane().add(JComboBoxPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 280, 40));

        TextValor.setText("0");
        TextValor.setToolTipText("");
        TextValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorActionPerformed(evt);
            }
        });
        getContentPane().add(TextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 280, 40));

        TextFormatedData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        TextFormatedData.setText("11/01/2001");
        TextFormatedData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFormatedDataActionPerformed(evt);
            }
        });
        getContentPane().add(TextFormatedData, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 280, 40));

        TextFormatedHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        TextFormatedHora.setText("10:20");
        getContentPane().add(TextFormatedHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 280, 40));

        TextObservacao.setColumns(20);
        TextObservacao.setRows(5);
        jScrollPane2.setViewportView(TextObservacao);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 460, 280));

        ButtonPedido.setBackground(new java.awt.Color(189, 168, 1));
        ButtonPedido.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ButtonPedido.setForeground(new java.awt.Color(174, 150, 0));
        ButtonPedido.setText("Pedido");
        ButtonPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 460, 50));

        TableListaPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cliente", "Pedido", "Valor", "Data", "Hora", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableListaPedido);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 890, 210));

        jLabelPainelPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/Pedidos-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabelPainelPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 50, 990, 700));

        LabelPedidoFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/fundoPedidos.jpg"))); // NOI18N
        getContentPane().add(LabelPedidoFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 1000));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPedidoActionPerformed
       this.controller.realizarPedido();
    }//GEN-LAST:event_ButtonPedidoActionPerformed

    private void TextValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorActionPerformed

    private void JComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBoxClienteActionPerformed

    private void JComboBoxPedidoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JComboBoxPedidoItemStateChanged
    
        this.controller.atualizaValor();
        
    }//GEN-LAST:event_JComboBoxPedidoItemStateChanged

    private void TextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdActionPerformed

    private void TextFormatedDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFormatedDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFormatedDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonPedido;
    private javax.swing.JComboBox<String> JComboBoxCliente;
    private javax.swing.JComboBox<String> JComboBoxPedido;
    private javax.swing.JLabel LabelCliente;
    private javax.swing.JLabel LabelConcluirPedido;
    private javax.swing.JLabel LabelData;
    private javax.swing.JLabel LabelHora;
    private javax.swing.JLabel LabelId;
    private javax.swing.JLabel LabelObservacao;
    private javax.swing.JLabel LabelPedido;
    private javax.swing.JLabel LabelPedidoFundo;
    private javax.swing.JLabel LabelValor;
    private javax.swing.JTable TableListaPedido;
    private javax.swing.JFormattedTextField TextFormatedData;
    private javax.swing.JFormattedTextField TextFormatedHora;
    private javax.swing.JTextField TextId;
    private javax.swing.JTextArea TextObservacao;
    private javax.swing.JTextField TextValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPainelPedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
       this.controller.atualizaTabela();
       this.controller.atualizaCliente();
       this.controller.atualizaPedido();
       this.controller.atualizaValor();
       
    }

    public JTable getTableListaPedido() {
        return TableListaPedido;
    }

    public void setTableListaPedido(JTable TableListaPedido) {
        this.TableListaPedido = TableListaPedido;
    }

    public JComboBox<String> getJComboBoxCliente() {
        return JComboBoxCliente;
    }

    public void setJComboBoxCliente(JComboBox<String> JComboBoxCliente) {
        this.JComboBoxCliente = JComboBoxCliente;
    }

    public JComboBox<String> getJComboBoxPedido() {
        return JComboBoxPedido;
    }

    public void setJComboBoxPedido(JComboBox<String> JComboBoxPedido) {
        this.JComboBoxPedido = JComboBoxPedido;
    }

    public JTextField getTextValor() {
        return TextValor;
    }

    public void setTextValor(JTextField TextValor) {
        this.TextValor = TextValor;
    }

    public JTextField getTextFormatedData() {
        JTextField jTextField1 = null;
        return jTextField1;
    }

    public void setTextFormatedData(JFormattedTextField TextFormatedData) {
        this.jTextField1 = TextFormatedData;
    }

    public JFormattedTextField getTextFormatedHora() {
        return TextFormatedHora;
    }

    public void setTextFormatedHora(JFormattedTextField TextFormatedHora) {
        this.TextFormatedHora = TextFormatedHora;
    }

    public JTextField getTextId() {
        return jTextField1;
    }

    public void setTextId(JTextField TextId) {
        this.jTextField1 = (JFormattedTextField) TextId;
    }

    public JTextArea getTextObservacao() {
        return TextObservacao;
    }

    public void setTextObservacao(JTextArea TextObservacao) {
        this.TextObservacao = TextObservacao;
    }
    
    
    
    
}
